spring: # Spring Boot configuration
  application: # Application configuration
    name: budget-buddy-backend-application # Name of the application
  datasource: # Database configuration
    url: jdbc:mysql://localhost:3306/budget_buddy # Database URL
    username: root # Database username
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect # Hibernate dialect for MySQL
    hibernate:
      ddl-auto: update # Automatically update the database schema
    show-sql: true # Show SQL statements in the console
    properties:
      hibernate.hibernate.format_sql : true # Format SQL statements for better readability
  mail:
    host: smtp-relay.brevo.com # SMTP server for sending emails
    port: 587 # SMTP port
    username: ${BREVO_USERNAME} # SMTP username (use environment variable for security)
    password: ${BREVO_PASSWORD} # SMTP password (use environment variable for security)
    properties:
      mail.smtp.auth: true # Enable SMTP authentication
      mail.smtp.starttls.enable: true # Enable STARTTLS for secure email transmission
      mail.smtp.from: ${BREVO_FROM_EMAIL} # Default "from" email address
    protocol: smtp

server: # Server configuration
  servlet: # Servlet configuration
    context-path: /api/v1.0 # Base path for all API endpoints

jwt:
  secret: ${JWT_SECRET}